### ISSUE TITLE
Suggested Metric: Mean Absolute Scaled Error

### ISSUE THREAD

**Issue by SteveBronder** [benhamner/Metrics#28]
Mean Absolute Scaled Error (MASE) is pretty widely used in econometrics and is one of the best known metrics for forecasting. I wanted to post that it may be appropriate for this package as well

http://robjhyndman.com/papers/foresight.pdf

**Comment by mfrasco** [comment]
Hi Steve. I am the new maintainer of the Metrics R package. I added MASE to version 0.1.3 of the package, which you can install from CRAN. If you have any questions, please free to create an issue at the [new home of the package](https://github.com/mfrasco/Metrics).

**Comment by SteveBronder** [comment]
Awesome thank you!
