### ISSUE TITLE
Become maintainer of this package

### ISSUE THREAD

**Issue by mfrasco** [benhamner/Metrics#41]
Hi

Do you have any interest in being the maintainer of this package? If not, would you mind if I help revive its status on CRAN?

Thanks
Michael Frasco

**Comment by ledell** [comment]
Hi Michael,

I was hoping that someone could take over maintenance of the package as well.  I opened an [issue](https://github.com/benhamner/Metrics/issues/34) about this back in April and have tried to get ahold of Ben on Github and on Twitter, but I haven't gotten a response.

I think if you don't hear back from him (seems like you haven't), you should definitely take it over!  That's what CRAN suggests for orphaned packages, so I don't think there's anything wrong with you doing so and it would be great to have this package be actively maintained. If you do decide to take it over, please read my comments on the [issue](https://github.com/benhamner/Metrics/issues/34) I opened and and take a look at my [fork](https://github.com/ledell/Metrics/commit/98a4cecec5f36ed713b9717b75d5e496e0c0d619) where I've fixed all the CRAN issues and added a bunch of code examples and documentation.  

Go Team Metrics!

**Comment by mfrasco** [comment]
Okay. That sounds great. I'll resubmit to CRAN soon. Thanks for writing all of those examples and documentation!

**Comment by mfrasco** [comment]
Metrics has been accepted to CRAN. The new github repo for the Metrics package is located here: https://github.com/mfrasco/Metrics
